name: riverweather
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - plotly
  - ipywidgets
  - jupyterlab
  - pip  
    - asyncio
    - playwright #need to also run 'install playwright', not sure how
